# Generated by Django 5.0.3 on 2024-04-25 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homiylar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('yangi', 'Yangi'), ('moderatsiya', 'Moderatsiyada'), ('tasdiqlangan', 'Tasdiqlangan'), ('atmen', 'Atmen')], default='yangi', max_length=100)),
                ('sponsr_type', models.CharField(choices=[('yuridik', 'Yuridik'), ('jismoniy', 'Jismoniy')], default='jismoniy', max_length=100)),
                ('payment_type', models.CharField(choices=[('naqd', 'Naqd'), ('plastik', 'Plastik')], default='plastik', max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('organization', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('kontrakt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Talaba_turi', models.CharField(choices=[('bakalvr', 'Bakalvr'), ('magistr', 'Magistr')], default='bakalvr', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SponsorStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.homiylar')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.talaba')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='talaba',
            name='otm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.university'),
        ),
    ]
