# Generated by Django 5.0.4 on 2024-05-04 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talaba',
            old_name='kontrakt',
            new_name='x',
        ),
        migrations.AlterField(
            model_name='sponsorstudent',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Sponsor_Student', to='app.homiylar'),
        ),
        migrations.AlterField(
            model_name='sponsorstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Sponsor_Student', to='app.talaba'),
        ),
    ]
