# Generated by Django 5.0.4 on 2024-05-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_kontrakt_talaba_x_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Homiylar',
            new_name='Sponsor',
        ),
        migrations.RenameModel(
            old_name='Talaba',
            new_name='Student',
        ),
    ]
